# Generated by Django 5.2.3 on 2025-11-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='db_name',
            field=models.CharField(blank=True, help_text='Database identifier for this company', max_length=100, null=True, unique=True),
        ),
    ]
