# Generated by Django 5.2.3 on 2025-11-28 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_version', models.CharField(default='1.0', max_length=50)),
                ('contract_text', models.TextField(help_text='Full contract text at time of acceptance')),
                ('agreed', models.BooleanField(default=False)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_agreements', to='subscription.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Agreement',
                'verbose_name_plural': 'Contract Agreements',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'user')},
            },
        ),
    ]
