# Generated by Django 5.2.3 on 2025-11-28 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_contractagreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('notification_type', models.CharField(choices=[('info', 'Məlumat'), ('warning', 'Xəbərdarlıq'), ('success', 'Uğur'), ('error', 'Xəta'), ('subscription', 'Abunəlik')], default='info', max_length=20, verbose_name='Növ')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunub')),
                ('is_important', models.BooleanField(default=False, verbose_name='Vacib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxunma tarixi')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='Əlaqəli link')),
                ('action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link mətni')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='subscription.company', verbose_name='Şirkət')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Göndərən')),
            ],
            options={
                'verbose_name': 'Bildiriş',
                'verbose_name_plural': 'Bildirişlər',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_read'], name='subscriptio_company_0c5dd9_idx'), models.Index(fields=['company', '-created_at'], name='subscriptio_company_8ade72_idx')],
            },
        ),
    ]
