# Generated by Django 5.2.3 on 2025-11-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Məsələn: Sistem işləməsi haqqında', max_length=200, verbose_name='Şablon adı')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('notification_type', models.CharField(choices=[('info', 'Məlumat'), ('warning', 'Xəbərdarlıq'), ('success', 'Uğur'), ('error', 'Xəta'), ('subscription', 'Abunəlik')], default='info', max_length=20, verbose_name='Növ')),
                ('is_important', models.BooleanField(default=False, verbose_name='Vacib')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='Əlaqəli link')),
                ('action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link mətni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bildiriş Şablonu',
                'verbose_name_plural': 'Bildiriş Şablonları',
                'ordering': ['name'],
            },
        ),
    ]
