# Generated by Django 5.2.3 on 2026-01-31 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_subscription_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='Fayl Yolu')),
                ('file_name', models.CharField(max_length=200, verbose_name='Fayl Adı')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Fayl Ölçüsü (bytes)')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('success', 'Uğurlu'), ('failed', 'Uğursuz')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xəta Mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='subscription.company', verbose_name='Şirkət')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backup-lar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('disabled', 'Deaktiv'), ('daily', 'Günlük'), ('weekly', 'Həftəlik'), ('monthly', 'Aylıq')], default='disabled', max_length=20, verbose_name='Backup Aralığı')),
                ('retention_days', models.IntegerField(default=30, help_text='Köhnə backup-lar neçə gün saxlanacaq', verbose_name='Saxlama Müddəti (gün)')),
                ('last_backup', models.DateTimeField(blank=True, null=True, verbose_name='Son Backup')),
                ('next_backup', models.DateTimeField(blank=True, null=True, verbose_name='Növbəti Backup')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_settings', to='subscription.company', verbose_name='Şirkət')),
            ],
            options={
                'verbose_name': 'Backup Parametrləri',
                'verbose_name_plural': 'Backup Parametrləri',
            },
        ),
    ]
