# Generated by Django 5.2.3 on 2025-11-28 07:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0006_alter_doctor_datasiya'),
        ('regions', '0004_alter_clinic_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDoctorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('drugs_data', models.JSONField(blank=True, default=dict)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('evvelki_borc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hesablanan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('silinen_miqdar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('avans', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('investisiya', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('geriqaytarma', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('datasiya', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('yekun_borc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='doctors.doctor')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_doctor_reports', to='regions.region')),
            ],
            options={
                'verbose_name': 'Aylıq Həkim Hesabatı (Bağlanmış)',
                'verbose_name_plural': 'Aylıq Həkim Hesabatları (Bağlanmış)',
                'ordering': ['-year', '-month', 'doctor__ad'],
                'unique_together': {('doctor', 'year', 'month')},
            },
        ),
    ]
