# Generated by Django 5.2.3 on 2025-11-24 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Şəhər Adı')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Şəhər Kodu')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Əhali Sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Şəhər',
                'verbose_name_plural': 'Şəhərlər',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bölgə Adı')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Bölgə Kodu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıqlama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'Bölgə',
                'verbose_name_plural': 'Bölgələr',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İxtisas Adı')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='İxtisas Kodu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıqlama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
            ],
            options={
                'verbose_name': 'İxtisas',
                'verbose_name_plural': 'İxtisaslar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Klinika Adı')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Klinika Kodu')),
                ('address', models.TextField(verbose_name='Ünvan')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Əlaqə Nömrəsi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('type', models.CharField(choices=[('hospital', 'Xəstəxana'), ('clinic', 'Klinika'), ('polyclinic', 'Poliklinika'), ('medical_center', 'Tibb Mərkəzi')], default='clinic', max_length=50, verbose_name='Növ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='regions.city', verbose_name='Şəhər')),
            ],
            options={
                'verbose_name': 'Klinika',
                'verbose_name_plural': 'Klinikalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='regions.region', verbose_name='Bölgə'),
        ),
    ]
