# Generated by Django 5.2.3 on 2025-11-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='population',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='code',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='email',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='description',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='updated_at',
        ),
    ]
