# Generated by Django 5.2.3 on 2025-11-24 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_remove_city_code_remove_city_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='code',
        ),
        migrations.AddField(
            model_name='clinic',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='regions.region', verbose_name='Bölgə'),
        ),
    ]
