# Generated by Django 5.2.3 on 2025-11-27 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_remove_clinic_created_at_remove_clinic_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='regions.region', verbose_name='Bölgə'),
        ),
    ]
