# Generated by Django 5.0.10 on 2026-02-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_alter_clinic_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Ünvan'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, help_text='Unikal kod (avtomatik yaradılır)', max_length=10, unique=True, verbose_name='Bölgə Kodu'),
        ),
    ]
