# Generated by Django 5.2.3 on 2025-11-24 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_alter_doctor_code'),
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarix')),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Xəstə Adı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Qeyd')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılıb')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənib')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.doctor', verbose_name='Həkim')),
            ],
            options={
                'verbose_name': 'Resept',
                'verbose_name_plural': 'Reseptlər',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Say')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Vahid Qiyməti')),
                ('dosage', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dozaj')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Müddət')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug', verbose_name='Dərman')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription', verbose_name='Resept')),
            ],
            options={
                'verbose_name': 'Resept Elementi',
                'verbose_name_plural': 'Resept Elementləri',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['-created_at'], name='prescriptio_created_92757f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor'], name='prescriptio_doctor__f96a16_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['date'], name='prescriptio_date_9e0859_idx'),
        ),
    ]
