# Generated by Django 5.2.3 on 2025-11-24 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
        ('regions', '0003_remove_clinic_created_at_remove_clinic_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='regions.region', verbose_name='Bölgə'),
        ),
    ]
