# Generated by Django 5.2.3 on 2025-11-24 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(help_text='Qısa ad', max_length=200, verbose_name='Ad')),
                ('tam_ad', models.CharField(help_text='Dərmanın tam adı', max_length=500, verbose_name='Tam Ad')),
                ('qiymet', models.DecimalField(decimal_places=2, help_text='Qiymət (AZN)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qiymət')),
                ('komissiya', models.DecimalField(decimal_places=2, help_text='Komissiya faizi (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Komissiya')),
                ('buraxilis_formasi', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Kapsul'), ('syrup', 'Sirop'), ('injection', 'İnyeksiya'), ('cream', 'Krem'), ('ointment', 'Məlhəm'), ('drops', 'Damcı'), ('spray', 'Sprey'), ('powder', 'Toz'), ('solution', 'Məhlul')], default='tablet', max_length=50, verbose_name='Buraxılış Forması')),
                ('dozaj', models.CharField(blank=True, help_text='Məsələn: 500mg, 10ml', max_length=200, null=True, verbose_name='Dozaj')),
                ('istehsalci', models.CharField(blank=True, max_length=200, null=True, verbose_name='İstehsalçı')),
                ('olke', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ölkə')),
                ('barkod', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barkod')),
                ('qeyd', models.TextField(blank=True, help_text='Əlavə qeydlər', null=True, verbose_name='Qeyd')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılıb')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənib')),
            ],
            options={
                'verbose_name': 'Dərman',
                'verbose_name_plural': 'Dərmanlar',
                'ordering': ['ad'],
                'indexes': [models.Index(fields=['ad'], name='drugs_drug_ad_bfe5c5_idx'), models.Index(fields=['buraxilis_formasi'], name='drugs_drug_buraxil_534b12_idx'), models.Index(fields=['is_active'], name='drugs_drug_is_acti_f63462_idx')],
            },
        ),
    ]
