# Generated by Django 5.2.3 on 2025-11-27 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='istehsalci',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='olke',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='qeyd',
        ),
        migrations.AlterField(
            model_name='drug',
            name='dozaj',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dozaj'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='komissiya',
            field=models.DecimalField(decimal_places=2, help_text='Komissiya məbləği (AZN olaraq)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Komissiya'),
        ),
    ]
