# Generated by Django 5.2.3 on 2025-11-24 07:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Həkim', 'verbose_name_plural': 'Həkimlər'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('A', 'A Kateqoriyası'), ('B', 'B Kateqoriyası'), ('C', 'C Kateqoriyası')], default='A', max_length=1, verbose_name='Kateqoriya'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='regions.city', verbose_name='Şəhər'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='regions.clinic', verbose_name='Klinika'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='code',
            field=models.CharField(default='000000', help_text='6 simvollu unikal kod', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='Həkim Kodu'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='datasiya',
            field=models.DateField(blank=True, null=True, verbose_name='Qeydiyyat Tarixi'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(choices=[('VIP', 'VIP'), ('I', 'I Dərəcə'), ('II', 'II Dərəcə'), ('III', 'III Dərəcə')], default='I', max_length=3, verbose_name='Dərəcə'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='evvelki_borc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Əvvəlki Borc'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('male', 'Kişi'), ('female', 'Qadın'), ('other', 'Digər')], default='male', max_length=10, verbose_name='Cinsiyyət'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hesablanmish_miqdar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Hesablanmış Miqdar'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='regions.region', verbose_name='Bölgə'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='silinen_miqdar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Silinən Miqdar'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yenilənmə Tarixi'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='yekun_borc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Yekun Borc'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='ad',
            field=models.CharField(max_length=200, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='ixtisas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='regions.specialization', verbose_name='İxtisas'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefon',
            field=models.CharField(max_length=50, verbose_name='Telefon Nömrəsi'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['code'], name='doctors_doc_code_c9d0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['ad'], name='doctors_doc_ad_3b82f6_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['region', 'city'], name='doctors_doc_region__aa7745_idx'),
        ),
    ]
