# Generated by Django 5.2.3 on 2025-11-24 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_options_doctor_category_doctor_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='code',
            field=models.CharField(blank=True, help_text='6 simvollu unikal kod (avtomatik yaradılır)', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='Həkim Kodu'),
        ),
    ]
