# Generated by Django 5.2.3 on 2025-11-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorpayment'),
        ('regions', '0004_alter_clinic_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Həkim Ödənişi', 'verbose_name_plural': 'Həkim Ödənişləri'},
        ),
        migrations.AddIndex(
            model_name='doctorpayment',
            index=models.Index(fields=['doctor', 'region'], name='doctors_doc_doctor__57b021_idx'),
        ),
    ]
