# Generated by Django 5.2.3 on 2025-11-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctorpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='datasiya',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Datasiya'),
        ),
    ]
