# Generated by Django 5.2.3 on 2026-02-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctor_datasiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('A*', 'A* Kateqoriyası'), ('A', 'A Kateqoriyası'), ('B', 'B Kateqoriyası'), ('C', 'C Kateqoriyası'), ('I ', 'I Kateqoriyası')], default='A', max_length=2, verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('male', 'Kişi'), ('female', 'Qadın')], default='male', max_length=10, verbose_name='Cinsiyyət'),
        ),
    ]
