# Generated by Django 5.2.3 on 2026-02-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_doctor_category_alter_doctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Kişi'), ('female', 'Qadın'), ('', 'Yox')], default='', max_length=10, verbose_name='Cinsiyyət'),
        ),
    ]
